
# Desarrollo por: Ing. Harry Morales
# Dpto. Sistemas UniMetro
#Cuando se despliega en tomacat se toma el puerto del servidor tomcat donde se despliega y se ig
#ignora esta propiedad [server.port]
server.port=8080 
spring.datasource.url=jdbc:mysql://localhost:3306/dashboard_unimetro
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.hibernate.show-sql=false
spring.hibernate.format_sql=true

#Maximo del archivo para cada request
spring.servlet.multipart.max-file-size=10MB
#Maximo del multipart
spring.servlet.multipart.max-request-size=10MB

# Hikari configurations
spring.datasource.initialize=false
spring.datasource.hikari.maximum-pool-size=200
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.idle-timeout=28790000

filesdir.root=/home/desarrollo/docsUploadFolder
filesdir.projects=projects
filesdir.profile_photos=user_photos
filesdir.digitalization=digitalization
filesdir.evidences=evidences
filesdir.approval_acts=approval_acts
filesdir.company_logo=company_logo
filesdir.photos_visit=photos_visit


logging.file.path=logs