
# Desarrollo por: Ing. Harry Morales
# Dpto. Sistemas - Naissant 2025

spring.datasource.url=jdbc:postgresql://localhost:54321/naissant
spring.datasource.username=naissant-dev
spring.datasource.password=naissant_p@ssw0rd

#190.131.239.203