
server.port=8085
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.hibernate.show-sql=false
spring.hibernate.format_sql=true

#Maximo del archivo para cada request
spring.servlet.multipart.max-file-size=10MB
#Maximo del multipart
spring.servlet.multipart.max-request-size=10MB

# Hikari configurations
spring.datasource.initialize=false
spring.datasource.hikari.maximum-pool-size=200
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.idle-timeout=28790000

filesdir.root=/home/desarrollo/docsUploadFolder
filesdir.profile_photos=user_photos
filesdir.company_logo=company_logo
filesdir.product_photos=product_photos
filesdir.permit_support=permit_support
filesdir.disability_support=disability_support
filesdir.digitalization_hv=digitalization_hv
filesdir.photos_visit=photos_visit


logging.file.path=logs